version: '3.8'

services:
  #custom image
  app:
    build:
      args:
        user: leonardo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: araujoleonardo/laravel-app
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    depends_on:
      - redis
      - queue
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - docker-laravel

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

  redis:
    image: redis:latest
    networks:
      - docker-laravel

  queue:
    build:
      args:
        user: leonardo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www/
    depends_on:
      - redis
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
