version: '3.8'

services:
  app-vue:
    build:
      context: .
      dockerfile: Dockerfile
    image: araujoleonardo/app-vue
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "serve"]
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge